---
title: "Novel"
author: "Hilary Killam"
date: "07/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(data.table)
library(readxl)
library(tidylog)
options(scipen=999)

```


```{r}
################################################# LOAD EYETRACKING DATA

#------------------------------------------------Load raw eyetracking data and create one file (large datasets)


#--------------------------------Read in all raw eyetracking datasets (2 for Novel, 2 for Foreign)
load(here("data/raw_eyetracking/noveldata1.Rda"))
load(here("data/raw_eyetracking/noveldata2.Rda"))
load(here("data/raw_eyetracking/foreigndata1.Rda"))
load(here("data/raw_eyetracking/foreigndata2.Rda"))

data_novel <- data_novel %>% mutate(tobii_session = "novel_1")
data_novel2 <- data_novel2 %>% mutate(tobii_session = "novel_2")
data_foreign <- data_foreign %>% mutate(tobii_session = "foreign_1")
data_foreign2 <- data_foreign2 %>% mutate(tobii_session = "foreign_2")


datasets1 <- list(data_novel, data_novel2) #make objects setparately because too large to row bind otherwise
datasets2 <- list(data_foreign, data_foreign2)

all_data <- datasets1 %>% map(select, -contains("AOI")) %>% reduce(bind_rows) # get rid of the many, many AOI columns
all_data2 <- datasets2 %>% map(select, -contains("AOI")) %>% reduce(bind_rows)

all_data <- all_data %>% bind_rows(all_data2) 


rm(datasets1, datasets2, all_data2, data_novel, data_novel2, data_foreign, data_foreign2) #get rid of things no longer needed



#--------------------------------Prep the data & get trial number


all_data <- all_data %>% select("tobii_session", "RecordingName", "RecordingDate", "LocalTimeStamp", "EyeTrackerTimestamp", "StudioTestName", "StudioEvent", "StudioEventData", "MediaName","RecordingTimestamp","ValidityLeft", "ValidityRight","GazePointX (ADCSpx)","GazePointY (ADCSpx)", "PupilLeft", "PupilRight") %>%  #all raw eyetracking data from Tobii for Novel and Foreign studies
  mutate(row_num = row_number(),
         MediaName = str_replace(MediaName, ".AVI", ""), #clean media names
         MediaName = str_replace(MediaName, ".wmv", ""),
         RecordingName = case_when( #fix some recording names that were entered differently for multiple recordings
    RecordingName == "NovelDom14_S31_44630" ~ "NovelDom_14_S32",
    RecordingName == "Foreign_14_S25_43549" ~ "NovelDom_14_S25",
    RecordingName == "Novel_14_S72" & StudioTestName == "Unmixed-2" ~ "Novel_14_S73",
    TRUE ~ RecordingName
  )) %>%
  rename(GazePointX = `GazePointX (ADCSpx)`, #rename gaze columns
         GazePointY = `GazePointY (ADCSpx)`) %>%
  mutate(trackloss = case_when(is.na(GazePointX) ~ TRUE, #missing gaze data is trackloss
                               is.na(GazePointY) ~ TRUE,
                               GazePointX < 0 | GazePointX > 1920 ~ TRUE, #gaze data outside range of screen is trackloss
                               GazePointY < 0 | GazePointY > 1200 ~ TRUE,
                               ValidityLeft > 1 & ValidityRight > 1 ~ TRUE, #low validity scores (which are higher than 1) are trackloss
                               TRUE ~ FALSE),
         timestamp_prev = lag(RecordingTimestamp, order_by = row_num), #figure out when each new recording starts (some kids had false starts)
         timestamp_prev = case_when(is.na(timestamp_prev) ~ 999999, #fix the first line which gets an NA for lag (any large # will do)
                                    TRUE ~ timestamp_prev),
         timestamp_diff = RecordingTimestamp - timestamp_prev,
         trial_group = paste0(RecordingName, MediaName)) %>% #create value that matches all rows for a given trial/kid
  mutate(new_recording = case_when(timestamp_diff < 0 ~ 1, TRUE ~ 0)) %>% #new recording starts whenever this is negative
  group_by(RecordingName) %>%
  mutate(recording_number = cumsum(new_recording == 1)) %>% #how many recordings does each kid have?
  mutate(trial_number = rleid(trial_group)) %>%
  group_by(RecordingName, trial_number, recording_number) %>%
  mutate(stimulus_length_ms = max(RecordingTimestamp) - min(RecordingTimestamp)) %>%
  ungroup() %>% 
  filter(MediaName != "attngetter169" & MediaName != "PrePost [final]", #get rid of attention getters and filter to rows with data
         !is.na(MediaName),
         MediaName != "",
         is.na(StudioEvent), #these rows have no gaze data
         !is.na(EyeTrackerTimestamp)) %>% #these rows have no gaze data and mess up the eyetrackingR functions
  group_by(RecordingName, recording_number) %>%
  mutate(trial_number = rleid(trial_number)) %>% #get final trial numbers, per recording
  ungroup() 

  

######################################################## CLEAN & MERGE

#------------------------------Clean up the data


all_data <- all_data %>% 
  clean_names() %>% 
  rename(id = recording_name,
         study_order = studio_test_name)  %>%
  mutate(#baby_id = str_extract(id, "\\d\\d\\d\\d\\d"), #not sure if necessary, many of these don't have baby ID
         study_id = str_extract(id, "S\\d\\d\\d"),
         study_id = case_when(is.na(study_id) ~ str_extract(id, "S\\d\\d"),
                                              TRUE ~ study_id),
         study_name = str_extract(id, "[^_]+"),
         study_name = str_remove(study_name, "14"),
         study_name = tolower(study_name),
         media_name = case_when(study_order == "E1" & trial_number == 17 ~ "KemPokyLeft", #fix several media names that are wrong
                                study_order == "E1" & trial_number == 20 ~ "KemPokyRight",
                                study_order == "E2" & trial_number == 18 ~ "KemPokyRight",
                                study_order == "E2" & trial_number == 19 ~ "KemPokyLeft",
                                study_order == "E3" & trial_number == 18 ~ "KemPokyLeft",
                                study_order == "E3" & trial_number == 19 ~ "KemPokyRight",
                                study_order == "F1" & trial_number == 17 ~ "KemPokyLeft",
                                study_order == "F1" & trial_number == 20 ~ "KemPokyRight",
                                study_order == "F2" & trial_number == 18 ~ "KemPokyRight",
                                study_order == "F2" & trial_number == 19 ~ "KemPokyLeft",
                                study_order == "F4" & trial_number == 17 ~ "KemPokyRight",
                                study_order == "F4" & trial_number == 20 ~ "KemPokyLeft",
                                TRUE ~ media_name)) %>% 
  select(-trial_group)

dataset <- all_data
save(dataset, file = here("data/all_novel_eyetracking.Rda"))

```
